export const RETRIEVE_QUESTIONS_BEGIN = 'RETRIEVE_QUESTIONS_BEGIN';
export const RETRIEVE_QUESTIONS_SUCCESS = 'RETRIEVE_QUESTIONS_SUCCESS';
export const RETRIEVE_QUESTIONS_FAILURE = 'RETRIEVE_QUESTIONS_SUCCESS';
